[package]
name = "test-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.13"
lazy_static = "1.1.1"
regex = "1.7"